name: docker-pr-build
on: 
  workflow_call:
    inputs:
      upstream:
        required: true
        type: string
      pr:
        required: true
        type: string
      prefix:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: ${{ inputs.prefix }}-pr-${{ inputs.pr }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: build and push alpine image
        uses: docker/build-push-action@v5
        with:
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
          build-args: |
            UPSTREAM_TYPE=${{ inputs.upstream }}
            TARGET_BRANCH=${{ inputs.pr }}