name: pr-build
on:
  workflow_dispatch:
    inputs:
      pr:
        description: upstream branch to pull from
        type: string
        required: true

permissions:
  packages: write
  contents: read

jobs:
  docker-alpine:
    uses: ./.github/workflows/pr-build.yml
    with:
      upstream: alpine-develop
      pr: ${{ inputs.pr }}
      prefix: alpine
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker-hwaccel:
    uses: ./.github/workflows/pr-build.yml
    with:
      upstream: hwaccel-develop
      pr: ${{ inputs.pr }}
      prefix: hwaccel
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}